//
// Test Bench Module Ori_Alon_Lab_1_lib.flags_module_tb.flags_module_tester
//
// Created:
//          by - vain.UNKNOWN (TOMER)
//          at - 20:07:07 02/ 5/2024
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module flags_module_tb;

// Local declarations
parameter DATA_WIDTH = 32;
parameter BUS_WIDTH = 64;
parameter MAX_DIM = (BUS_WIDTH / DATA_WIDTH);

// Internal signal declarations
wire clk_i;
wire rst_ni;
wire write_enable_i;
wire write_data_i;
wire read_data_o;


flags_module #(32,64,(BUS_WIDTH / DATA_WIDTH)) U_0(
   .clk_i          (clk_i),
   .rst_ni         (rst_ni),
   .write_enable_i (write_enable_i),
   .write_data_i   (write_data_i),
   .read_data_o    (read_data_o)
);

flags_module_tester #(32,64,(BUS_WIDTH / DATA_WIDTH)) U_1(
   .clk_i          (clk_i),
   .rst_ni         (rst_ni),
   .write_enable_i (write_enable_i),
   .write_data_i   (write_data_i),
   .read_data_o    (read_data_o)
);

endmodule // flags_module_tb


