//
// Test Bench Module Ori_Alon_Lab_1_lib.flags_module_tester.flags_module_tester
//
// Created:
//          by - vain.UNKNOWN (TOMER)
//          at - 20:07:07 02/ 5/2024
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps
module flags_module_tester (clk_i,
                            rst_ni,
                            write_enable_i,
                            write_data_i,
                            read_data_o
                           );

// Local declarations

parameter DATA_WIDTH = 32;
parameter BUS_WIDTH = 64;
localparam MAX_DIM = (BUS_WIDTH / DATA_WIDTH);



output clk_i;
output rst_ni;
output write_enable_i;
output write_data_i;
input  read_data_o;

wire clk_i;
wire rst_ni;
wire write_enable_i;
wire write_data_i;
wire read_data_o;

initial begin: clk_setup
  clk_i <= 0;
  forever clk_i <= ~clk_i;
end

task insert_flags;
input [MAX_DIM^2-1:0] flags;
begin
  write_enable_i = 1'b0;
  #1
  write_enable_i = 1'b1;
  #1;
  write_enable_i = 1'b0;
end
endtask

initial begin
  insert_flags(2);
end

endmodule // flags_module_tester


