//
// Test Bench Module Ori_Alon_Lab_1_lib.pe_module_tb.pe_module_tester
//
// Created:
//          by - orisad.UNKNOWN (TOMER)
//          at - 22:31:00 01/18/2024
//
// Generated by Mentor Graphics' HDL Designer(TM) 2019.2 (Build 5)
//
`resetall
`timescale 1ns/10ps

module pe_module_tb;
  
  
// Local declarations
parameter DATA_WIDTH = 32;

// Internal signal declarations
wire clk_i;
wire rst_ni;
wire [DATA_WIDTH-1:0]a_i;
wire [DATA_WIDTH-1:0]b_i;
wire start_i;
wire [DATA_WIDTH-1:0]a_o;
wire [DATA_WIDTH-1:0]b_o;
wire [2*DATA_WIDTH-1:0]res_o;
wire overflow_o;
 


pe_module #(DATA_WIDTH) U_0(
   .clk_i  (clk_i),
   .rst_ni (rst_ni),
   .a_i    (a_i),
   .b_i    (b_i),
   .start_i (start_i),
   .a_o    (a_o),
   .b_o    (b_o),
   .res_o  (res_o),
   .overflow_o (overflow_o)
);

pe_module_tester #(DATA_WIDTH) U_1(
   .clk_i  (clk_i),
   .rst_ni (rst_ni),
   .a_i    (a_i),
   .b_i    (b_i),
   .start_i (start_i),
   .a_o    (a_o),
   .b_o    (b_o),
   .res_o  (res_o),
   .overflow_o (overflow_o)
);
  

endmodule // pe_module_tb


